# Generated by Django 4.2 on 2023-04-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LernModulesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name module')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description module')),
                ('number', models.CharField(max_length=32, verbose_name='Number module')),
            ],
        ),
    ]
