# Generated by Django 4.2 on 2023-04-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lern_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lernmodulesmodel',
            options={'verbose_name': 'Lern Module', 'verbose_name_plural': 'Lern Modules'},
        ),
    ]
